### ISSUE TITLE
no module on dist folder

### ISSUE THREAD

**Issue by grazianogrespan** [prashantsaini1/android-titanium-imagecropper#1]
Hello @prashantsaini1 , thank you for your module.
On the dist folder the zipped module has zero byte dimension, probably an issue on the commit procedure.
Could you rebuild the module ?

**Comment by prashantsaini1** [comment]
Hey, are you not able to see the module? I can see it. Here's the screenshot of **dist** directory
![screen shot 2017-11-21 at 9 22 50 pm](https://user-images.githubusercontent.com/20779626/33082255-5192fbba-cf02-11e7-9ed6-6f7b69ad38c6.png)

**Comment by prashantsaini1** [comment]
Hey, thanks for pointing that error 👍 . I have added the correct compiled module. Note that you will need to add those two properties in your tiapp.xml file in order to force Ti SDK to use JDK 1.8 compiler. Here's a ticket mentioned for same reason : https://jira.appcelerator.org/browse/TIMOB-25448

As soon as Ti SD 7.0.0.GA is out, I will publish the updated module so users don't need to add these properties.

**Comment by grazianogrespan** [comment]
perfect! thank you very much.

Il 21 nov 2017 17:17, Prashant Saini <notifications@github.com> ha scritto:

Hey, thanks for pointing that error 👍 . I have added the correct compiled module. Note that you will need to add those two properties in your tiapp.xml file in order to force Ti SDK to use JDK 1.8 compiler. Here's a ticket mentioned for same reason : https://jira.appcelerator.org/browse/TIMOB-25448

As soon as Ti SD 7.0.0.GA is out, I will publish the updated module so users don't need to add these properties.
